export const FETCH_INSURE_PLAN = 'VEHICLE.FETCH_INSURE_PLAN'

export const CHANGE_PLAN_FORCE = 'VEHICLE.CHANGE_PLAN_FORCE'

export const CHANGE_SELECTED_PLAN = 'VEHICLE.CHANGE_SELECTED_PLAN'

export const CHANGE_SELECTED_PLAN_OPTION = 'VEHICLE.CHANGE_SELECTED_PLAN_OPTION'

export const FETCH_ORDER_INSURANT = 'VEHICLE.FETCH_INSURANT'

export const FETCH_ORDER_APPLICANT = 'VEHICLE.FETCH_ORDER_APPLICANT'
